@hostname = http://localhost:9999
# @hostname = http://localhost:8080



###
# @prompt apelido
# @prompt nome
POST {{hostname}}/pessoas HTTP/1.1
content-type: application/json

{
    "apelido" : "{{apelido}}",
    "nome" : "{{nome}}",
    "nascimento" : "1985-09-23",
    "stack" : null
}

###
POST {{hostname}}/pessoas HTTP/1.1
content-type: application/json

{
    "apelido" : "any1",
    "nome" : "bruno",
    "nascimento" : "1985-09-23",
    "stack" : ["Node", "Go"]
}

###
GET {{hostname}}/pessoas/1ceb0515-de55-406e-a93d-251e5ecc48e2 HTTP/1.1

###
GET {{hostname}}/contagem-pessoas HTTP/1.1

###
GET {{hostname}}/pessoas/?t=a HTTP/1.1

###
GET {{hostname}}/pessoas HTTP/1.1